spring:
  datasource:
    url: jdbc:mysql://payment-mysql-db:3306/payment
    username: root
    password: payment!2#
    driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true